### PR TITLE
Allow new cvmfs-libs package

### PR DESCRIPTION
**Pull request by traylenator**
#### Pull Request (PR) description
Since cvmfs 2.10.0 was released the cvmfs packages have spawned a new sub package cvmfs-libs.

On RedHat where the package list is restricted allow this package to be installed.

Resolves

```
Aug 16 16:57:15 lx.example.ch dnf-distro-sync[1230631]:   - cannot install the best update candidate for package cvmfs-2.10.1-1.el9.x86_64
Aug 16 16:57:15 lx.example.ch dnf-distro-sync[1230631]:   - package cvmfs-libs-2.11.0-1.el9.x86_64 is filtered out by exclude filtering
```

#### This Pull Request (PR) fixes the following issues
Fixes #179
Fixes #181 
Fixes #183

### CODE REVIEW

**Comment by traylenator** [comment]
Hmm, 

All Debian familes are failing with:

```
 Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: W: GPG error: https://cvmrepo.s3.cern.ch/cvmrepo/apt focal-prod Release: The following signatures were invalid: BADSIG 230D389D8AE45CE7 CernVM Administrator (cvmadmin) <cernvm.administrator@cern.ch>
  Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: E: The repository 'https://cvmrepo.s3.cern.ch/cvmrepo/apt focal-prod Release' is not signed.
  ```

**Comment by olifre** [comment]
> All Debian familes are failing with:

It seems the repo is borked:
```
$ curl -v https://cvmrepo.s3.cern.ch/cvmrepo/apt/dists/bullseye-prod/Release.gpg
...
< last-modified: Tue, 28 Feb 2023 09:28:27 GMT
...
$ curl https://cvmrepo.s3.cern.ch/cvmrepo/apt/dists/bullseye-prod/Release
...
Date: Wed, 16 Aug 2023 10:24:12 +0000
...
```
i.e. the GPG signature for the `Release` file was not updated, but the `Release` file was modified.

**Comment by olifre** [comment]
@traylenator I've dropped a note to `cvmfs-talk@cern.ch` right now, we can probably just re-run CI here once the repos are fixed :wink:.

**Comment by traylenator** [comment]
Has to be away to re-run all the tests - not just one by one ....

**Pull request merged**
