### PR TITLE
Check that cvmfs_cache_base directory exists

### LINKED ISSUE #153: Facter error if cvmfs has never been mounted
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.17.0
- Ruby: ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-linux]
- Distribution: Ubuntu 20.04
- Module version: 8.1.0

## How to reproduce (e.g Puppet code you use)\

Any use of module, without mounting cvmfs.

## What are you seeing

Error message appears when `/etc/cvmfs/cvmfsfacts.yaml` has been created but cvmfs never mounted.

## What behaviour did you expect instead

No error message should appear.

## Output log

```
2022-06-24 18:01:24 erc-hpc-comp001 INFO puppet-agent[3377379]: Using environment 'production'
2022-06-24 18:01:24 erc-hpc-comp001 INFO puppet-agent[3377379]: Retrieving pluginfacts
2022-06-24 18:01:24 erc-hpc-comp001 INFO puppet-agent[3377379]: Retrieving plugin
2022-06-24 18:01:25 erc-hpc-comp001 INFO puppet-agent[3377379]: Loading facts
2022-06-24 18:01:29 erc-hpc-comp001 ERR puppet-agent[3377379]: (Facter) Error while resolving custom fact fact='cvmfspartsize', resolution='<anonymous>': undefined method `split' for nil:NilClass
```

## Any additional information you'd like to impart

PR for fix to follow.

### PR DESCRIPTION
**Pull request by xandm**
If cvmfs has been installed but never mounted/used, it will not, triggering the following error:
```Error: Facter: Error while resolving custom fact fact='cvmfspartsize', resolution='<anonymous>': undefined method `split' for nil:NilClass```

#### Pull Request (PR) description

Fix facter error when cvmfs has been installed but never mounted.

#### This Pull Request (PR) fixes the following issues
Fixes #153

### CODE REVIEW

**Comment by traylenator** [comment]
Hi @xandm seems fine, can you rebase to get rid of the rubocop error - thanks.

**Comment by bastelfreak** [comment]
@xandm can you please rebase against our latest master branch? (and not do a merge commit). If you've any questions about it or need some help, you can hop into our IRC channel #voxpupuli on Libera.chat or the #voxpupuli slack channel on https://puppetcommunity.slack.com/

**Comment by jcpunk** [comment]
@xandm any chance to get this sorted?

**Comment by jcpunk** [comment]
Resolved in #160

**Pull request closed without merging**
